# nodejs
[nodejs]
format = "via [â¬¢ $version](bold green) "

# git branch
[git_branch]
symbol = "[îœ¥ ](bold green)"
format = "on [$symbol[$branch ](bold green)(:$remote_branch)]($style)"


# git commit
[git_commit]
tag_symbol = "ï’ "

# git status
[git_status]
conflicted = "î«¾ "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
up_to_date = "î®± "
stashed = "îœ‚ "
modified = "ğŸ“"
staged = '[î©¤ ++$count](green)'
renamed = "ğŸ‘…"
deleted = " îª "
